scholarshipportal/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("", include("website.urls", namespace="website")),
    path("", include("accounts.urls")),
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("accounts/", include("allauth.urls")),
    path("summernote/", include("django_summernote.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path

from .views import (
    dashboard_redirector_view,
    StudentDashboardView,
    StaffDashboardView,
    NoticeBoardView,
    ChangePasswordView,
    ScholarshipListView,
    MCMTietApplicationView,
    MCMAlumniApplicationView,
    MCMOtherApplicationView,
    ApplicationsListView,
    GrievanceSubmitView,
    GrievanceListView,
    AccountSettingsView,
    ScholarshipCalculatorView,
    ReportsView,
    UploadScholarshipsView,
    UploadAccountsView, MyScholarshipsView, AutomaticMerit12View, AutomaticMerit3View
)

app_name = "website"

urlpatterns = [
    path("", dashboard_redirector_view, name="landing-page"),
    path(
        "student-dashboard/", StudentDashboardView.as_view(), name="student-dashboard"
    ),
    path("staff-dashboard/", StaffDashboardView.as_view(), name="staff-dashboard"),
    path("notice-board/", NoticeBoardView.as_view(), name="notice-board"),
    path("change-password/", ChangePasswordView.as_view(), name="change-password"),
    path("scholarships/", ScholarshipListView.as_view(), name="scholarship-list"),
    path(
        "scholarships/mcm_tiet/<int:scholarship_id>/apply/",
        MCMTietApplicationView.as_view(),
        name="mcm-tiet-apply",
    ),
    path(
        "scholarships/mcm_alumni/<int:scholarship_id>/apply/",
        MCMAlumniApplicationView.as_view(),
        name="mcm-alumni-apply",
    ),
    path(
        "scholarships/mcm_other/<int:scholarship_id>/apply/",
        MCMOtherApplicationView.as_view(),
        name="mcm-other-apply",
    ),
    path("my-applications/", ApplicationsListView.as_view(), name="applications-list"),
    path(
        "grievance/submit/", GrievanceSubmitView.as_view(), name="grievance-submit-view"
    ),
    path("grievances/", GrievanceListView.as_view(), name="grievance-list-view"),
    path(
        "account/settings/", AccountSettingsView.as_view(), name="account-settings-view"
    ),
    path(
        "scholarship-calculator",
        ScholarshipCalculatorView.as_view(),
        name="scholarship-calculator",
    ),
    path("reports/", ReportsView.as_view(), name="reports"),
    path("upload-scholarship/", UploadScholarshipsView.as_view(), name='upload-scholarship-data'),
    path("upload-account/", UploadAccountsView.as_view(), name='upload-account-data'),
    path("my-scholarships/", MyScholarshipsView.as_view(), name='my-scholarships'),

    path("auto-merit-1-2/", AutomaticMerit12View.as_view(), name='auto-merit-1-2'),
    path("auto-merit-3/", AutomaticMerit3View.as_view(), name='auto-merit-3'),
]

website/models.py
from uuid import uuid4

import pdfkit
from django.conf import settings
from django.contrib.staticfiles import finders
from django.core.validators import (
    MaxValueValidator,
    MinValueValidator,
    FileExtensionValidator,
)
from django.db import models
from django.template.loader import render_to_string

from accounts.models import UserAccount, Student, Session

STATE_CHOICES = (
    ("Andhra Pradesh", "Andhra Pradesh"),
    ("Arunachal Pradesh", "Arunachal Pradesh"),
    ("Assam", "Assam"),
    ("Bihar", "Bihar"),
    ("Chhattisgarh", "Chhattisgarh"),
    ("Goa", "Goa"),
    ("Gujarat", "Gujarat"),
    ("Haryana", "Haryana"),
    ("Himachal Pradesh", "Himachal Pradesh"),
    ("Jharkhand", "Jharkhand"),
    ("Karnataka", "Karnataka"),
    ("Kerala", "Kerala"),
    ("Madhya Pradesh", "Madhya Pradesh"),
    ("Maharashtra", "Maharashtra"),
    ("Manipur", "Manipur"),
    ("Meghalaya", "Meghalaya"),
    ("Mizoram", "Mizoram"),
    ("Nagaland", "Nagaland"),
    ("Odisha", "Odisha"),
    ("Punjab", "Punjab"),
    ("Rajasthan", "Rajasthan"),
    ("Sikkim", "Sikkim"),
    ("Tamil Nadu", "Tamil Nadu"),
    ("Telangana", "Telangana"),
    ("Tripura", "Tripura"),
    ("Uttarakhand", "Uttarakhand"),
    ("Uttar Pradesh", "Uttar Pradesh"),
    ("West Bengal", "West Bengal"),
    ("Andaman and Nicobar Islands", "Andaman and Nicobar Islands"),
    ("Chandigarh", "Chandigarh"),
    (
        "Dadra and Nagar Haveli and Daman & Diu",
        "Dadra and Nagar Haveli and Daman & Diu",
    ),
    ("The Government of NCT of Delhi", "The Government of NCT of Delhi"),
    ("Jammu & Kashmir", "Jammu & Kashmir"),
    ("Ladakh", "Ladakh"),
    ("Lakshadweep", "Lakshadweep"),
    ("Puducherry", "Puducherry"),
)


class Constraint(models.Model):
    name = models.CharField(max_length=1024)
    description = models.TextField(blank=True, null=True)
    required = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class ScholarshipCategory(models.Model):
    name = models.CharField(max_length=1024)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Scholarship Categories"


class Scholarship(models.Model):
    class ScholarshipType(models.IntegerChoices):
        # NOTE: don't change the integer values
        MCM_TIET = 1
        MCM_ALUMNI = 2
        MCM_OTHER = 3
        MERIT_ALUMNI = 4
        MERIT_AUTO = 5

    name = models.CharField(max_length=200)
    category = models.ForeignKey(ScholarshipCategory, on_delete=models.CASCADE)
    scholarship_type = models.IntegerField(choices=ScholarshipType.choices)

    eligibility_criteria = models.TextField()
    number_of_scholarships = models.CharField(max_length=1024)
    value_of_scholarship = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    constraints = models.ManyToManyField(Constraint, through="ScholarshipConstraint")

    def __str__(self):
        return self.name

    @property
    def verbose_type(self):
        if self.scholarship_type == 1:
            return "MCM_TIET"
        elif self.scholarship_type == 2:
            return "MCM_ALUMNI"
        elif self.scholarship_type == 3:
            return "MCM_OTHER"
        elif self.scholarship_type == 4:
            return "MERIT_ALUMNI"
        else:
            return "MERIT_AUTO"


class ScholarshipConstraint(models.Model):
    scholarship = models.ForeignKey(Scholarship, on_delete=models.CASCADE)
    constraint = models.ForeignKey(Constraint, on_delete=models.CASCADE)
    min_value = models.FloatField(blank=True, null=True)
    max_value = models.FloatField(blank=True, null=True)

    def __str__(self):
        return f"{self.constraint.name} constraint on [{self.scholarship.name}]"


class MCMTietApplication(models.Model):
    """Scholarship Type: MCM_TIET = 1"""

    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    scholarship = models.ForeignKey(Scholarship, on_delete=models.CASCADE)
    contact_number = models.PositiveIntegerField()
    alternate_contact_number = models.PositiveIntegerField()
    state_of_residence = models.CharField(choices=STATE_CHOICES, max_length=255)

    class_12_marks = models.CharField(
        max_length=255, help_text="Enter percentage e.g. 89.8 "
    )  # % or CGPA
    current_cgpa_or_rank = models.CharField(
        max_length=255, help_text="Current CGPA or Rank or Diploma %"
    )

    family_income_per_mcm_application = models.CharField(
        max_length=255, help_text="FAMILY INCOME AS MENTIONED IN MCM APPLICATION FORM"
    )
    family_income_per_affidavit = models.CharField(
        max_length=255, help_text="FAMILY INCOME AS PER AFFIDAVIT ATTACHED"
    )
    family_income_per_certificate = models.CharField(
        max_length=255, help_text="FAMILY INCOME AS PER CERTIFICATE OF TEHSILDAR"
    )
    bank_balance = models.IntegerField()
    fdr_balance = models.CharField(max_length=255, help_text="")

    itr_annual_year_current = models.IntegerField(help_text="ITR for this annual year")
    itr_annual_year_last = models.IntegerField(help_text="ITR for previous annual year")
    itr_annual_year_last_last = models.IntegerField(
        help_text="ITR for last to last annual year"
    )

    immovable_property = models.BooleanField(
        help_text="IMMOVABLE PROPERTY AS PER AFFIDAVIT"
    )
    single_girl_child = models.BooleanField(help_text="Are you a Single Girl Child?")

    applied_for_mcp_special = models.BooleanField(help_text="APPLIED FOR MCM SPECIAL?")
    mcp_special_reason = models.TextField(
        help_text="SPECIFIC REASON FOR APPLYING MCM SPECIAL?", blank=True, null=True
    )

    applied_for_other_scholarship = models.BooleanField(
        help_text="HAVE YOU APPLIED FOR ANY OTHER SCHOLARSHIP?"
    )
    other_scholarship_details = models.TextField(
        help_text="DETAILS OF OTHER SCHOLARSHIP APPLIED", blank=True, null=True
    )

    previous_year_scholarship = models.BooleanField(
        help_text="HAVE YOU RECEIVED ANY SCHOLARSHIP IN THE PREVIOUS YEAR?"
    )
    previous_year_scholarship_details = models.TextField(
        help_text="DETAILS OF PREVIOUS SCHOLARSHIP RECEIVED", blank=True, null=True
    )
    previous_year_scholarship_amount = models.IntegerField(
        help_text="AMOUNT OF THE PREVIOUS SCHOLARSHIP", blank=True, null=True
    )

    income_certificate = models.FileField(
        help_text="Please upload a digital / scanned copy of your income certificate",
        upload_to="income_certificates",
        validators=[
            FileExtensionValidator(allowed_extensions=["pdf", "jpg", "png", "jpeg"])
        ],
    )
    supporting_documents = models.FileField(
        help_text="Please upload supporting documents in a .zip format, if any",
        blank=True,
        null=True,
        upload_to="supporting_documents",
    )

    declaration = models.BooleanField(
        help_text="I acknowledge that i have read all the eligibility criteria of scholarship and i am eligible for "
                  "applying to TIET Merit-cum-means scholarship."
    )

    status = models.CharField(
        max_length=1024,
        default="PENDING",
        choices=(
            ("PENDING", "PENDING"),
            ("APPROVED", "APPROVED"),
            ("REJECTED", "REJECTED"),
        ),
    )
    remarks = models.TextField(blank=True, null=True)

    # TODO: fill more fields, https://docs.google.com/forms/d/e/1FAIpQLScSaU3NGIu13V4j9fEi5B1Djl503c72o9sZ-9YsVY1_hsM4aA/viewform

    def __str__(self):
        return f"Application for [{self.scholarship.name[:15]}...]"

    class Meta:
        verbose_name_plural = "Merit cum Means Applications"
        verbose_name = "Merit cum means Application"


class MCMAlumniApplication(models.Model):
    """Scholarship Type: MCM_ALUMNI = 2"""

    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    scholarship = models.ForeignKey(Scholarship, on_delete=models.CASCADE)

    photograph = models.FileField(
        help_text="Passport size photograph in JPG/PNG under 2 MB.",
        blank=True,
        null=True,
        upload_to="photographs",
    )

    roll_no = models.CharField(max_length=20, help_text="Registration/Roll No")
    personal_contact_number = models.PositiveIntegerField()
    year = models.CharField(max_length=20, help_text="Year")
    branch = models.CharField(max_length=20, help_text="Branch")

    jee_main_rank = models.CharField(max_length=255, help_text="JEE Main Rank")
    current_cgpa = models.CharField(max_length=255, help_text="Current CGPA")

    father_name = models.CharField(max_length=255, help_text="Father's Name")
    father_profession = models.CharField(
        max_length=255, help_text="Father's Profession"
    )
    father_contact_number = models.PositiveIntegerField(
        help_text="Father's Contact Number"
    )

    mother_name = models.CharField(max_length=255, help_text="Mother's Name")
    mother_profession = models.CharField(
        max_length=255, help_text="Mother's Profession"
    )

    mother_contact_number = models.PositiveIntegerField(
        help_text="Mother's Contact Number"
    )

    family_income_per_annum = models.CharField(
        max_length=255, help_text="Family income per annum"
    )

    bank_name = models.CharField(max_length=255, help_text="Student's Bank Name")
    bank_account_number = models.CharField(
        max_length=255, help_text="Bank Savings Account Number"
    )
    banK_address = models.CharField(max_length=255, help_text="Bank Branch Address")
    bank_ifsc_code = models.CharField(max_length=255, help_text="Bank IFSC Code")

    declaration = models.BooleanField(
        help_text="I acknowledge that I have read all the eligibility criteria of this scholarship and I am eligible "
                  "for applying to this scholarship."
    )

    status = models.CharField(
        max_length=1024,
        default="PENDING",
        choices=(

website/forms.py
from django.contrib.auth.forms import AdminPasswordChangeForm
from django.forms import ModelForm, Form

from website.models import (
    MCMTietApplication,
    Grievance,
    MCMAlumniApplication,
    MCMOtherApplication,
)


class UserPasswordChangeForm(AdminPasswordChangeForm):
    def save(self, commit=True):
        password = self.cleaned_data["password1"]
        self.user.set_password(password)
        if commit:
            self.user.save()
        return self.user


class MCMAlumniApplicationForm(ModelForm):
    class Meta:
        model = MCMAlumniApplication
        fields = "__all__"

        exclude = ("remarks", "status")

    def __init__(self, student_id, scholarship_id, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["student"].value = student_id
        self.fields["student"].initial = student_id
        self.fields["student"].disabled = True
        self.fields["declaration"].required = True
        self.fields["scholarship"].value = scholarship_id
        self.fields["scholarship"].initial = scholarship_id
        self.fields["scholarship"].disabled = True


class MCMOtherApplicationForm(ModelForm):
    class Meta:
        model = MCMOtherApplication
        fields = "__all__"

        exclude = ("remarks", "status")

    def __init__(self, student_id, scholarship_id, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["student"].value = student_id
        self.fields["student"].initial = student_id
        self.fields["student"].disabled = True
        self.fields["declaration"].required = True
        self.fields["scholarship"].value = scholarship_id
        self.fields["scholarship"].initial = scholarship_id
        self.fields["scholarship"].disabled = True


class MCMTietApplicationForm(ModelForm):
    class Meta:
        model = MCMTietApplication
        fields = "__all__"

        exclude = ("remarks", "status")

    def __init__(self, student_id, scholarship_id, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["student"].value = student_id
        self.fields["student"].initial = student_id
        self.fields["student"].disabled = True
        self.fields["declaration"].required = True
        self.fields["scholarship"].value = scholarship_id
        self.fields["scholarship"].initial = scholarship_id
        self.fields["scholarship"].disabled = True


class GrievanceForm(ModelForm):
    class Meta:
        model = Grievance
        fields = "__all__"
        exclude = ("date_opened", "resolved", "remarks")

    def __init__(self, student_id, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["student"].value = student_id
        self.fields["student"].initial = student_id
        self.fields["student"].disabled = True

website/templates/pages/change-password.html
{% extends 'student-dashboard-base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block sidebars %}{{ block.super }}

    {% include 'partials/sidebar.html' with page='change_password' %}
{% endblock %}

{% block mainSection %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4 mb-3">
        <div class="d-block mb-4 mb-md-0">

            <h2 class="h4">Change password</h2>
            <p class="mb-0">Using this form, you can change / set a new password, if not already set. </p>
        </div>

    </div>
    <div class="d-block mb-4">
        <form method="post">
            {% csrf_token %}
            {{ form | crispy }}
            <button class="btn btn-primary" type="submit">Save</button>
        </form>
    </div>
{% endblock %}

website/templates/pages/mcm-application-form.html
{% extends 'student-dashboard-base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block sidebars %}{{ block.super }}

    {% include 'partials/sidebar.html' with page='' %}
{% endblock %}

{% block mainSection %}
    {{ form.errors }}
    <div class="mt-4 mb-1"><a href="{% url 'website:scholarship-list' %}"><h6 class="m-0 font-weight-bold text-primary">
        << Go
        back to
        scholarship list</h6>
    </a></div>
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center  mb-4">
        <div class="d-block mb-4 mb-md-0">

            <h2 class="h4">Application form for "{{ scholarship.name }}"</h2>
            <p class="mb-0">Using this form, you can apply for the merit-cum-means scholarship </p>
        </div>

    </div>
    <div class="d-block mb-4">

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form | crispy }}
            <button class="btn btn-primary" type="submit">Save</button>
        </form>
    </div>
{% endblock %}

website/templates/pages/scholarship-list.html
{% extends 'student-dashboard-base.html' %}

{% block sidebars %}
    {{ block.super }}
    {% include 'partials/sidebar.html' with page="scholarships" %}
{% endblock %}

{% block customStyles %}
    <style>
        .accordion-button {
            position: relative;
            display: flex;
            align-items: center;
            width: 100%;
            padding: 1rem 1.25rem;
            font-size: 1rem;
            color: #374151;
            text-align: left;
            background-color: rgba(0, 0, 0, 0);
            border: 0;
            border-radius: 0;
            overflow-anchor: none;
            transition: color 0.15s ease-in-out, background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out, border-radius 0.15s ease
        }

        @media (prefers-reduced-motion: reduce) {
            .accordion-button {
                transition: none
            }
        }

        .accordion-button:not(.collapsed) {
            color: #4B5563;
            background-color: #F2F4F6;
            box-shadow: inset 0 -.0625rem 0 #E5E7EB
        }

        .accordion-button:not(.collapsed)::after {
            background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%234B5563'%3e%3cpath fill-rule='evenodd' d='M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z'/%3e%3c/svg%3e");
            transform: rotate(180deg)
        }

        .accordion-button::after {
            flex-shrink: 0;
            width: 1.25rem;
            height: 1.25rem;
            margin-left: auto;
            content: "";
            background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23374151'%3e%3cpath fill-rule='evenodd' d='M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z'/%3e%3c/svg%3e");
            background-repeat: no-repeat;
            background-size: 1.25rem;
            transition: transform 0.2s ease-in-out
        }

        @media (prefers-reduced-motion: reduce) {
            .accordion-button::after {
                transition: none
            }
        }

        .accordion-button:hover {
            z-index: 2
        }

        .accordion-button:focus {
            z-index: 3;
            border-color: #4d6689;
            outline: 0;
            box-shadow: 0 0 0 .18rem rgba(31, 41, 55, 0.25)
        }

        .list-group-item {
            border-bottom: 0.05rem solid lightgray !important;
        }
    </style>
{% endblock %}

{% block mainSection %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4 mb-3">
        <div class="d-block mb-4 mb-md-0">

            <h2 class="h4">Available scholarships</h2>
            <p class="mb-0">SCHOLARSHIPS / TUITION FREESHIPS FOR THE CURRENT SESSION </p>
        </div>

    </div>
    <div class="d-block mb-4">
        <div class="accordion" id="accordionExample">
            {% for category in object_list %}
                <div class="accordion-item active">
                    <h2 class="accordion-header" id="headingOne">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapse_{{ category.id }}" aria-expanded="true"
                                aria-controls="collapse_{{ category.id }}">
                            {{ category.name }}
                        </button>
                    </h2>
                    <div id="collapse_{{ category.id }}"
                         class="accordion-collapse collapse {% if forloop.counter == 1 %}show{% endif %}"
                         aria-labelledby="headingOne"
                         data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            {% for scholarship in category.scholarship_set.all %}
                                <div class="card mb-3">
                                    <div class="card-header bg-secondary text-white px-3 pt-3 pb-1">
                                        <h5>{{ scholarship.name }}</h5>
                                    </div>
                                    <ul class="list-group list-group-flush">
                                        <li class="list-group-item">
                                            <b>Total Number of
                                                scholarships:</b> {{ scholarship.number_of_scholarships }}</li>
                                        <li class="list-group-item"><b>Value of
                                            scholarship:</b> {{ scholarship.value_of_scholarship }}</li>
                                        <li class="list-group-item">
                                            <b>Type of scholarship:</b> {{ scholarship.verbose_type }}
                                        </li>
                                        <li class="list-group-item"><b>How to apply: </b>
                                            {% if scholarship.scholarship_type == 1 %}
                                                <a href="{% url 'website:mcm-tiet-apply' scholarship.id %}"
                                                   class="btn ms-1 btn-sm btn-primary">Apply here</a>

                                            {% elif scholarship.scholarship_type == 2 %}
                                                <a href="{% url 'website:mcm-alumni-apply' scholarship.id %}"
                                                   class="btn ms-1 btn-sm btn-primary">Apply here</a>

                                            {% elif scholarship.scholarship_type == 3 %}
                                                <a href="{% url 'website:mcm-other-apply' scholarship.id %}"
                                                   class="btn ms-1 btn-sm btn-primary">Apply here</a>

                                            {% else %}
                                                Allotted automatically. No need to apply.
                                            {% endif %}
                                        </li>
                                    </ul>


                                    <div class="card-text p-4">
                                        <p><b>Eligibility Criteria:</b></p>
                                        {{ scholarship.eligibility_criteria | safe }}
                                    </div>

                                </div>
                                <hr>
                            {% endfor %}

                        </div>
                    </div>
                </div>

            {% endfor %}


        </div>
    </div>

{% endblock %}

website/templates/pages/student-dashboard.html
{% extends 'student-dashboard-base.html' %}

{% block sidebars %}
    {{ block.super }}
    {% include 'partials/sidebar.html' with page="index" %}
{% endblock %}
{% block mainSection %}

    <div class="py-4 d-flex justify-content-start">
        <div class="dropdown">
            <a href="{% url 'website:scholarship-calculator' %}"
               class="btn btn-primary text-white d-inline-flex align-items-center me-2 "
               aria-haspopup="true" aria-expanded="false">
                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor"
                     class="bi bi-credit-card-2-back-fill icon icon-xs me-2" viewBox="0 0 16 16">
                    <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v5H0V4zm11.5 1a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h2a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-2zM0 11v1a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-1H0z"></path>
                </svg>
                Scholarship Eligibility Calculator
            </a>

        </div>
    </div>

    {#  Info Cards  #}
    <div class="row">
        <div class="col-lg-4 col-sm-6 col-12">
            <div class="card mb-2 mb-md-4">
                <div class="card-content">
                    <div class="card-body">
                        <div class="media d-flex">
                            <div class="media-body text-right">
                                <h3>{{ user.last_login.date }}</h3>
                                <span>Last Login</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-sm-6 col-12">
            <div class="card mb-2 mb-md-4">
                <div class="card-content">
                    <div class="card-body">
                        <div class="media d-flex">
                            <div class="media-body text-right">
                                <h3>{{ user.student.branch_code }}</h3>
                                <span>Branch</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-sm-6 col-12">
            <div class="card mb-2 mb-md-4">
                <div class="card-content">
                    <div class="card-body">
                        <div class="media d-flex">
                            <div class="media-body text-right">
                                <h3>{{ user.student.roll_no }}</h3>
                                <span>Roll Number</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>

    <div class="row">
        <div class="col-12 mb-4">
            <div class="card border-0 shadow">
                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col">
                            <h2 class="fs-5 fw-bold mb-0">Notice Board</h2>
                        </div>
                        <div class="col text-end">
                            <a href="{% url 'website:notice-board' %}" class="btn btn-sm btn-primary">See all</a>
                        </div>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                        <tr>
                            <th class="border-bottom" scope="col">S.No.</th>
                            <th class="border-bottom" scope="col" style="width: 60%">Name</th>
                            <th class="border-bottom" scope="col">Category</th>
                            <th class="border-bottom" scope="col">Date</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for notice in notices %}

                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td scope="row">
                                    <a
                                            {% if notice.attachment %}href="{{ notice.attachment.url }}"
                                            target="_blank"{% endif %}

                                            class="fw-bolder ">{{ notice.title }}</a>
                                </th>
                                <td class="fw-bolder text-gray-500">
                                    {{ notice.category.title }}
                                </td>
                                <td class="fw-bolder text-gray-500">
                                    {{ notice.date.date }}
                                </td>

                            </tr>

                        {% endfor %}


                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>


{% endblock %}