scholarshipportal/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("", include("website.urls", namespace="website")),
    path("", include("accounts.urls")),
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("accounts/", include("allauth.urls")),
    path("summernote/", include("django_summernote.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path

from .views import (
    dashboard_redirector_view,
    StudentDashboardView,
    StaffDashboardView,
    NoticeBoardView,
    ChangePasswordView,
    ScholarshipListView,
    MCMTietApplicationView,
    MCMAlumniApplicationView,
    MCMOtherApplicationView,
    ApplicationsListView,
    GrievanceSubmitView,
    GrievanceListView,
    AccountSettingsView,
    ScholarshipCalculatorView,
    ReportsView,
    UploadScholarshipsView,
    UploadAccountsView, MyScholarshipsView, AutomaticMerit12View, AutomaticMerit3View
)

app_name = "website"

urlpatterns = [
    path("", dashboard_redirector_view, name="landing-page"),
    path(
        "student-dashboard/", StudentDashboardView.as_view(), name="student-dashboard"
    ),
    path("staff-dashboard/", StaffDashboardView.as_view(), name="staff-dashboard"),
    path("notice-board/", NoticeBoardView.as_view(), name="notice-board"),
    path("change-password/", ChangePasswordView.as_view(), name="change-password"),
    path("scholarships/", ScholarshipListView.as_view(), name="scholarship-list"),
    path(
        "scholarships/mcm_tiet/<int:scholarship_id>/apply/",
        MCMTietApplicationView.as_view(),
        name="mcm-tiet-apply",
    ),
    path(
        "scholarships/mcm_alumni/<int:scholarship_id>/apply/",
        MCMAlumniApplicationView.as_view(),
        name="mcm-alumni-apply",
    ),
    path(
        "scholarships/mcm_other/<int:scholarship_id>/apply/",
        MCMOtherApplicationView.as_view(),
        name="mcm-other-apply",
    ),
    path("my-applications/", ApplicationsListView.as_view(), name="applications-list"),
    path(
        "grievance/submit/", GrievanceSubmitView.as_view(), name="grievance-submit-view"
    ),
    path("grievances/", GrievanceListView.as_view(), name="grievance-list-view"),
    path(
        "account/settings/", AccountSettingsView.as_view(), name="account-settings-view"
    ),
    path(
        "scholarship-calculator",
        ScholarshipCalculatorView.as_view(),
        name="scholarship-calculator",
    ),
    path("reports/", ReportsView.as_view(), name="reports"),
    path("upload-scholarship/", UploadScholarshipsView.as_view(), name='upload-scholarship-data'),
    path("upload-account/", UploadAccountsView.as_view(), name='upload-account-data'),
    path("my-scholarships/", MyScholarshipsView.as_view(), name='my-scholarships'),

    path("auto-merit-1-2/", AutomaticMerit12View.as_view(), name='auto-merit-1-2'),
    path("auto-merit-3/", AutomaticMerit3View.as_view(), name='auto-merit-3'),
]

website/forms.py
from django.contrib.auth.forms import AdminPasswordChangeForm
from django.forms import ModelForm, Form

from website.models import (
    MCMTietApplication,
    Grievance,
    MCMAlumniApplication,
    MCMOtherApplication,
)


class UserPasswordChangeForm(AdminPasswordChangeForm):
    def save(self, commit=True):
        password = self.cleaned_data["password1"]
        self.user.set_password(password)
        if commit:
            self.user.save()
        return self.user


class MCMAlumniApplicationForm(ModelForm):
    class Meta:
        model = MCMAlumniApplication
        fields = "__all__"

        exclude = ("remarks", "status")

    def __init__(self, student_id, scholarship_id, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["student"].value = student_id
        self.fields["student"].initial = student_id
        self.fields["student"].disabled = True
        self.fields["declaration"].required = True
        self.fields["scholarship"].value = scholarship_id
        self.fields["scholarship"].initial = scholarship_id
        self.fields["scholarship"].disabled = True


class MCMOtherApplicationForm(ModelForm):
    class Meta:
        model = MCMOtherApplication
        fields = "__all__"

        exclude = ("remarks", "status")

    def __init__(self, student_id, scholarship_id, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["student"].value = student_id
        self.fields["student"].initial = student_id
        self.fields["student"].disabled = True
        self.fields["declaration"].required = True
        self.fields["scholarship"].value = scholarship_id
        self.fields["scholarship"].initial = scholarship_id
        self.fields["scholarship"].disabled = True


class MCMTietApplicationForm(ModelForm):
    class Meta:
        model = MCMTietApplication
        fields = "__all__"

        exclude = ("remarks", "status")

    def __init__(self, student_id, scholarship_id, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["student"].value = student_id
        self.fields["student"].initial = student_id
        self.fields["student"].disabled = True
        self.fields["declaration"].required = True
        self.fields["scholarship"].value = scholarship_id
        self.fields["scholarship"].initial = scholarship_id
        self.fields["scholarship"].disabled = True


class GrievanceForm(ModelForm):
    class Meta:
        model = Grievance
        fields = "__all__"
        exclude = ("date_opened", "resolved", "remarks")

    def __init__(self, student_id, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["student"].value = student_id
        self.fields["student"].initial = student_id
        self.fields["student"].disabled = True

website/views.py
import json
import math
from io import BytesIO

from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import ValidationError
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.validators import FileExtensionValidator
from django.db import transaction, IntegrityError
from django.db.models import Sum
from django.http import HttpResponse
from django.shortcuts import redirect, get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, FormView, CreateView
from numpy import mat
from oauthlib.oauth2.rfc6749.errors import LoginRequired

from accounts.models import UserAccount, Student, Session

from website.forms import (
    UserPasswordChangeForm,
    MCMTietApplicationForm,
    MCMOtherApplicationForm,
    MCMAlumniApplicationForm,
    GrievanceForm,

)

from website.mixins import StudentRequired, StaffRequired
from website.models import (
    Scholarship,
    NoticeCategory,
    ScholarshipCategory,
    Notice,
    MCMTietApplication,
    MCMOtherApplication,
    MCMAlumniApplication,
    Grievance,
    Constraint,
    ReceivedScholarship, ExcelError, CertificateRequest,
)

import pandas as pd


@login_required
def dashboard_redirector_view(request):
    if request.user.is_student():
        return redirect("website:student-dashboard")
    elif request.user.is_staff_member:
        return redirect("website:staff-dashboard")
    else:
        return HttpResponse("You do not have permission to access this page.")


class StudentDashboardView(StudentRequired, TemplateView):
    template_name = "pages/student-dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["notices"] = Notice.objects.all().order_by("-date")[:10]
        return context


class StaffDashboardView(StaffRequired, TemplateView):
    template_name = "pages/staff-dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["user_count"] = UserAccount.objects.filter(
            role=UserAccount.STUDENT
        ).count()
        context["scholarships"] = Scholarship.objects.all()
        return context


class ReportsView(StaffRequired, TemplateView):
    template_name = "pages/reports.html"

    def get_context_data(self, **kwargs):
        context = super(ReportsView, self).get_context_data(**kwargs)
        context["user_count"] = Student.objects.all().count()
        amount = (
                ReceivedScholarship.objects.all().aggregate(Sum("amount"))["amount__sum"]
                or 0
        )
        context["scholarship_amount"] = f'{amount:,}'
        context["scholarship_count"] = ReceivedScholarship.objects.all().count()
        context["scholarship_percentage"] = (
                Student.objects.filter(receivedscholarship__isnull=False).count()
                / Student.objects.all().count()
                * 100
        )
        context["female_count"] = Student.objects.filter(
            receivedscholarship__isnull=False, sex="F"
        ).count()
        context["male_count"] = Student.objects.filter(
            receivedscholarship__isnull=False, sex="M"
        ).count()
        context["sessions"] = Session.objects.all()
        historical_data = []

        for i, session in enumerate(Session.objects.all().order_by("-name")):
            amount = (
                    ReceivedScholarship.objects.filter(session=session).aggregate(
                        Sum("amount")
                    )["amount__sum"]
                    or 0
            )
            historical_data.append(
                {"id": i, "session": session.name, "scholarship_amount": amount}
            )

        context["historical_data"] = historical_data
        return context

    def post(self, *args, **kwargs):
        session_id = self.request.POST.get("session")
        session = get_object_or_404(Session, pk=session_id)
        io = BytesIO()
        writer = pd.ExcelWriter(io)

        branches = (
            ReceivedScholarship.objects.order_by("branch")
            .values_list("branch", flat=True)
            .distinct()
        )

        for branch in branches:
            scholarships = ReceivedScholarship.objects.filter(
                branch=branch, session=session
            )
            prepped_dataset = []

            for s in scholarships:
                prepped_dataset.append(
                    {
                        "Name": s.student.user.first_name
                                + " "
                                + s.student.user.last_name,
                        "Roll No": s.student.roll_no,
                        "E-mail": s.student.user.email,
                        "Received Scholarship": s.scholarship.name,
                        "Scholarship Type": s.scholarship.verbose_type,
                        "Amount": s.amount,
                        "current_cgpa": s.current_cgpa,
                        "cgpa_1st_semester": s.cgpa_1st_semester,
                        "cgpa_2nd_semester": s.cgpa_2nd_semester,
                        "cgpa_3rd_semester": s.cgpa_3rd_semester,
                        "sgpa_5th_semester": s.sgpa_5th_semester,
                        "sgpa_6th_semester": s.sgpa_6th_semester,
                        "agpa": s.agpa,
                        "marks": s.marks,
                        "jee_rank": s.jee_rank,
                        "pcme_percentage": s.pcme_percentage,
                        "pcb_percentage": s.pcb_percentage,
                        "ti_rank": s.ti_rank,
                        "tu_rank": s.tu_rank,
                        "twelfth_overall_percentage": s.twelfth_overall_percentage,
                    }
                )

            df = pd.DataFrame(prepped_dataset)

            df = df.dropna(axis=1, how="all")
            df.to_excel(writer, sheet_name=branch, index=False)
            # Auto-adjust columns' width
            for column in df:
                column_width = (
                        max(df[column].astype(str).map(len).max(), len(column)) + 10
                )
                col_idx = df.columns.get_loc(column)
                writer.sheets[branch].set_column(col_idx, col_idx, column_width)

        writer.close()

        resp_file = io.getvalue()
        response = HttpResponse(resp_file, content_type="application/ms-excel")
        response[
            "Content-Disposition"
        ] = f"attachment; filename=Scholarship Report {session.name}.xls"
        return response


class UploadScholarshipsView(StaffRequired, TemplateView):
    template_name = "pages/upload-scholarship-data.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['sessions'] = Session.objects.all()
        context['scholarship_categories'] = ScholarshipCategory.objects.all()
        context['scholarships'] = Scholarship.objects.all()
        return context

    def post(self, request, **kwargs):
        messages.error(request, "Server error 500. Please contact administrator")
        return self.render_to_response(self.get_context_data())


class AutomaticMerit12View(StaffRequired, TemplateView):
    template_name = "pages/automatic-merit-1-2.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['sessions'] = Session.objects.all()
        return context

    def return_error(self, error):
        messages.error(self.request, error)
        return self.render_to_response(self.get_context_data())

    def post(self, request, **kwargs):
        try:
            FileExtensionValidator(allowed_extensions=['xls', 'xlsx'])(request.FILES.get("file"))
        except ValidationError as e:
            return self.return_error(str(e))

        try:
            error_list = []
            context = self.get_context_data()

            excel_file: InMemoryUploadedFile = self.request.FILES.get("file")

            if not excel_file:
                self.return_error("Excel file could not be read. Please try again")

            parsed_excel = pd.ExcelFile(excel_file)

            branch_sheet = pd.read_excel(parsed_excel, 'Branches', na_filter=False)

            branches = []
            error = False
            for index, row in branch_sheet.iterrows():
                row_id = str(int(str(index)) + 2)

                if not row['Tution Fees'] or not row['Development Fees'] or not row['Branch']:
                    error_list.append(ExcelError("Branches: Row " + row_id,
                                                 "Branch Name, Tution Fees and Development Fees are required."))
                    error = True
                    continue

                branches.append({
                    'name': row['Branch'],
                    'tf': row['Tution Fees'],
                    'df': row['Development Fees']
                })

            if error:
                context['error_list'] = error_list
                return self.render_to_response(context)

            students = []
            branch_names = [x['name'] for x in branches]
            student_sheet = pd.read_excel(parsed_excel, 'Students', na_filter=False)
            for index, row in student_sheet.iterrows():
                row_id = str(int(str(index)) + 2)
                local_error = False

                for column in ['REGNO', 'STUDENTNAME', 'Branch', 'QUOTA', 'Backlogs', 'AGPA', 'Marks']:
                    local_error = self.ensure_not_null(column, error_list, row, row_id)
                local_error = local_error or self.ensure_roll_no_exists(row, row_id, "Students", error_list)

                if row['Branch'] not in branch_names:

website/templates/partials/footer.html
<footer class="bg-white rounded shadow p-4 mb-4 mt-4 ">
    <div class="row">
        <div class="col-12">
            <p class="mb-0" style="width: 100%">All rights reserved  ©<span class="current-year"></span> | <a
                    class="text-primary fw-normal" href="https://thapar.edu" target="_blank">Thapar.edu</a></p>
        </div>

    </div>
</footer>

website/templates/partials/mcm-submitted-alumni.html
<tr>
    <td><a href="#">MCM-ALUMNI-{{ application.id }}</a></td>
    <td>{{ application.scholarship.name }}</td>
    <td>
        <button type="button"
                class="btn btn-sm btn-{% if application.status == 'PENDING' %}warning{% elif application.status == 'REJECTED' %}danger{% else %}success{% endif %}">
            {{ application.status }}</button>
    </td>
    <td>
        <div class="row">
            <div class="col-12">
                <button type="button" class="btn btn-outline-info me-2  mb-3"
                        data-bs-toggle="modal"
                        data-bs-target="#alummodal-{{ application.id }}-details">View
                    Details
                </button>
                <div class="modal fade" id="alummodal-{{ application.id }}-details"
                     tabindex="-1"
                     style="display: none;"
                     aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header"><h2
                                    class="h6 modal-title">Application Details</h2>
                                <button type="button" class="btn-close"
                                        data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                            </div>
                            <div class="modal-body text-wrap">
                                <p><b>Scholarship
                                    Name: </b> {{ application.scholarship.name }}
                                </p>

                                <hr>
                                <p><b>Roll No: </b> {{ application.roll_no }}</p>
                                <p><b>Contact No: </b> {{ application.personal_contact_number }}</p>
                                <p><b>Year: </b> {{ application.year }}</p>
                                <p><b>Branch: </b> {{ application.branch }}</p>
                                <p><b>JEE Main Rank: </b> {{ application.jee_main_rank }}</p>
                                <p><b>CGPA: </b> {{ application.current_cgpa }}</p>
                                <hr>
                                <p><b>Father's Name: </b> {{ application.father_name }}</p>
                                <p><b>Father's Profession: </b> {{ application.father_profession }}</p>
                                <p><b>Father's Contact Number: </b> {{ application.father_contact_number }}</p>
                                <p><b>Mother's Name: </b> {{ application.mother_name }}</p>
                                <p><b>Mother's Profession: </b> {{ application.mother_profession }}</p>
                                <p><b>Mother's Contact Number: </b> {{ application.mother_contact_number }}</p>
                                <p><b>Family Income / Year: </b> {{ application.family_income_per_annum }}</p>
                                <hr>
                                <p><b>Student's Bank Name: </b> {{ application.bank_name }}</p>
                                <p><b>Bank Savings Account Number: </b> {{ application.bank_account_number }}</p>
                                <p><b>Bank Branch Address: </b> {{ application.banK_address }}</p>
                                <p><b>Bank IFSC Code: </b> {{ application.bank_ifsc_code }}</p>
                                <hr>


                            </div>
                            <div class="modal-footer">

                                <button type="button" class="btn btn-secondary"
                                        data-bs-dismiss="modal">Close
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <button class="btn btn-outline-secondary mb-3 me-2" type="button"
                        data-bs-toggle="modal"
                        data-bs-target="#alummodal-{{ application.id }}-remarks">
                    View Remarks
                </button>
                <div class="modal fade" id="alummodal-{{ application.id }}-remarks"
                     tabindex="-1"
                     style="display: none;"
                     aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header"><h2
                                    class="h6 modal-title">Remarks</h2>
                                <button type="button" class="btn-close"
                                        data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                            </div>
                            <div class="modal-body text-wrap">
                                {% if application.remarks %}
                                    {{ application.remarks | safe }} {% else %} There are no
                                    remarks
                                    yet.{% endif %}
                            </div>
                            <div class="modal-footer">

                                <button type="button" class="btn btn-secondary"
                                        data-bs-dismiss="modal">Close
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                {% if  application.status == 'PENDING' %}
                    <button class="btn btn-danger mb-3" type="button"
                            data-bs-toggle="modal"
                            data-bs-target="#alummodal-{{ application.id }}-withdraw">
                        Withdraw Application
                    </button>{% endif %}
                <div class="modal fade" id="alummodal-{{ application.id }}-withdraw"
                     tabindex="-1"
                     style="display: none;"
                     aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header"><h2
                                    class="h6 modal-title">Are you sure?</h2>
                                <button type="button" class="btn-close"
                                        data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                            </div>
                            <div class="modal-body text-wrap">
                                This action cannot be undone. If you withdraw the
                                application, you will need to resubmit a new
                                application.
                            </div>
                            <div class="modal-footer">

                                <button type="button" class="btn btn-outline-secondary"
                                        data-bs-dismiss="modal">Cancel
                                </button>
                                <form action="" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="application_id"
                                           value="{{ application.id }}">
                                    <button type="submit" class="btn btn-danger">
                                        Withdraw
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </td>
</tr>

website/templates/partials/message-alerts.html
{% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message  | safe }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}

website/templates/partials/mobile-navbar.html
{% load static %}
<nav class="navbar navbar-dark navbar-theme-primary px-4 col-12 d-lg-none">
    <a class="navbar-brand me-lg-5" href="#">
       <h5 class="text-white">Scholarship Portal</h5>
    </a>
    <div class="d-flex align-items-center">
        <button class="navbar-toggler d-lg-none collapsed" type="button" data-bs-toggle="collapse"
                data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</nav>

website/templates/partials/navbar.html
{% load static %}
<nav class="navbar  navbar-top navbar-expand navbar-dashboard navbar-light ps-0 pe-2 pb-0">
    <div class="container-fluid px-0">
        <div class="d-flex justify-content-between w-100" id="navbarSupportedContent">
            <div class="d-flex align-items-center">
                <!-- Search form -->
                <form class="navbar-search form-inline" id="navbar-search-main">
                    <div class="input-group input-group-merge search-bar">
              <span class="input-group-text" id="topbar-addon">
                <svg class="icon icon-xs" x-description="Heroicon name: solid/search" xmlns="http://www.w3.org/2000/svg"
                     viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd"
                        d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                        clip-rule="evenodd"></path>
                </svg>
              </span>
                        <input type="text" class="form-control" id="topbarInputIconLeft" placeholder="Search"
                               aria-label="Search" aria-describedby="topbar-addon" name="query">
                    </div>
                </form>
                <!-- / Search form -->
            </div>
            <!-- Navbar links -->
            <ul class="navbar-nav align-items-center justify-content-center">
                {% if user.is_authenticated %}
                    <li class=" dropdown ms-lg-3">
                        <a class="nav-link dropdown-toggle pt-1 px-0" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            <div class="media d-flex align-items-center">

                                <img class="avatar rounded-circle" alt="Image placeholder"
                                     src="{% static 'dist/assets/img/icons/undraw_profile.svg' %}">
                                <div class="media-body ms-2 text-dark align-items-center d-none d-lg-block">
                                    <span class="mb-0 font-small fw-bold text-gray-900"
                                          style="color: black;">{% if user.first_name %}{{ user.first_name }}
                                        {{ user.last_name }}{% else %}{{ user.email }}{% endif %}</span>

                                </div>

                            </div>
                        </a>
                        <div class="dropdown-menu dashboard-dropdown dropdown-menu-end mt-2 py-1">

                            {% if user.is_student %}
                                <a class="dropdown-item d-flex align-items-center"
                                   href="{% url 'website:account-settings-view' %}">
                                    <svg class="dropdown-icon text-gray-400 me-2" fill="currentColor"
                                         viewBox="0 0 20 20"
                                         xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd"
                                              d="M11.49 3.17c-.38-1.56-2.6-1.56-2.98 0a1.532 1.532 0 01-2.286.948c-1.372-.836-2.942.734-2.106 2.106.54.886.061 2.042-.947 2.287-1.561.379-1.561 2.6 0 2.978a1.532 1.532 0 01.947 2.287c-.836 1.372.734 2.942 2.106 2.106a1.532 1.532 0 012.287.947c.379 1.561 2.6 1.561 2.978 0a1.533 1.533 0 012.287-.947c1.372.836 2.942-.734 2.106-2.106a1.533 1.533 0 01.947-2.287c1.561-.379 1.561-2.6 0-2.978a1.532 1.532 0 01-.947-2.287c.836-1.372-.734-2.942-2.106-2.106a1.532 1.532 0 01-2.287-.947zM10 13a3 3 0 100-6 3 3 0 000 6z"
                                              clip-rule="evenodd"></path>
                                    </svg>
                                    Settings
                                </a>
                            {% endif %}

                            <a class="dropdown-item d-flex align-items-center"
                               href="{% url 'website:change-password' %}">
                                <svg class="dropdown-icon text-gray-400 me-2" fill="currentColor" viewBox="0 0 20 20"
                                     xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd"
                                          d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-2 0c0 .993-.241 1.929-.668 2.754l-1.524-1.525a3.997 3.997 0 00.078-2.183l1.562-1.562C15.802 8.249 16 9.1 16 10zm-5.165 3.913l1.58 1.58A5.98 5.98 0 0110 16a5.976 5.976 0 01-2.516-.552l1.562-1.562a4.006 4.006 0 001.789.027zm-4.677-2.796a4.002 4.002 0 01-.041-2.08l-.08.08-1.53-1.533A5.98 5.98 0 004 10c0 .954.223 1.856.619 2.657l1.54-1.54zm1.088-6.45A5.974 5.974 0 0110 4c.954 0 1.856.223 2.657.619l-1.54 1.54a4.002 4.002 0 00-2.346.033L7.246 4.668zM12 10a2 2 0 11-4 0 2 2 0 014 0z"
                                          clip-rule="evenodd"></path>
                                </svg>
                                Change Password
                            </a>
                            <div role="separator" class="dropdown-divider my-1"></div>
                            <a class="dropdown-item d-flex align-items-center" href="{% url 'logout' %}">
                                <svg class="dropdown-icon text-danger me-2" fill="none" stroke="currentColor"
                                     viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                          d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path>
                                </svg>
                                Logout
                            </a>
                        </div>
                    </li>
                {% else %}
                    <a class="btn btn-primary" href="/sign-in" type="button">Sign in </a>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>